# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  ##########################
  # Instructions
  ##########################
  #
  # Follow instructions specific to each section.
  # Project IDs must follow the rules below, additionally,
  # if a gatekeeper policy is used to enforce specific naming conventions, refer to its documentation.
  #   - All IDs should be universally unique.
  #   - Must be 6 to 30 characters in length.
  #   - Can only contain lowercase letters, numbers, and hyphens.
  #   - Must start with a letter.
  #   - Cannot end with a hyphen.
  #   - Cannot be in use or previously used; this includes deleted projects.
  #   - Cannot contain restricted strings, such as google and ssl.
  #
  ##########################
  # Client
  ##########################
  #
  # Name for the client, lowercase only
  # customization: required
  client-name: 'client1'
  #
  # Clients Billing Account ID to associate with the client-landing-zone resources. The client-name-projects-sa will need billing user role permission granted.
  # customization: required
  client-billing-id: "AAAAAA-BBBBBB-CCCCCC"
  #
  # group to grant viewer permission on client folder
  # customization: required
  client-folderviewer: 'group:client1@example.com'
  #
  ##########################
  # Logging
  ##########################
  #
  # logging project id created in core-landing-zone
  # customization: required
  logging-project-id: logging-project-12345
  #
  # LoggingLogBucket retention settings
  # Set the number of days to retain logs in Cloud Logging buckets
  # Set the lock mechanism on the bucket to: true or false
  # After a retention policy is locked (true), you can't delete the bucket until every log in the bucket has fulfilled the bucket's retention period
  # AU-9 PROTECTION OF AUDIT INFORMATION
  # AU-11 AUDIT RECORD RETENTION
  # The values below must be modified to retention-locking-policy: true in a Production setting to implement above mentioned security controls.
  # customization: required
  retention-locking-policy: "false"
  #
  # The values below must be modified to retention-in-days: 365 in a Production setting to implement above mentioned security controls.
  # customization: required
  retention-in-days: "1"
  #
  ##########################
  # Network Host Project (standard)
  ##########################
  #
  # the network host project id that will be created
  # customization: required
  host-project-id: net-host-project-12345
  #
  # Org policy exception to allow vpc peering between a defined list and the host project.
  # The file is located here client-folder/standard/application-infrastructure/host-project/org-policies/exceptions/compute-restrict-vpc-peering-except-host-project.yaml
  # Warning ! this file is commented out by default. You will need to customize this setter only if you enable it.
  # The allowed/denied list of networks must be identified in the form:
  # under:organizations/ORGANIZATION_ID, under:folders/FOLDER_ID, under:projects/PROJECT_ID,
  # or projects/PROJECT_ID/global/networks/NETWORK_NAME.
  # customization: required
  project-allowed-restrict-vpc-peering: |
    - under:projects/PROJECT_ID
  #
  # nonp IP space
  standard-nonp-cidr: 10.1.0.0/18
  #
  # Subnet IP range for nonp-main in northamerica-northeast1
  standard-nane1-nonp-main-snet: 10.1.0.0/21
  #
  # Subnet IP range for nonp-main in northamerica-northeast2
  standard-nane2-nonp-main-snet: 10.1.8.0/21
  #
  # pbmm IP space
  standard-pbmm-cidr: 10.1.128.0/18
  #
  # Subnet IP range for pbmm-main in northamerica-northeast1
  standard-nane1-pbmm-main-snet: 10.1.128.0/21
  #
  # Subnet IP range for pbmm-main in northamerica-northeast2
  standard-nane2-pbmm-main-snet: 10.1.136.0/21
  #
  # A list of internal IP ranges used by firewall rules
  firewall-internal-ip-ranges: |
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 240.0.0.0/4
  #
  ##########################
  # Firewall Policy (client-folder)
  ##########################
  #
  # Deny sanctioned countries ingress traffic
  # https://cloud.google.com/firewall/docs/firewall-policies-rule-details#geo-location-object
  # https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
  # The list below MUST BE reconfigured. If the value stays XX it will fail reconciliation with an error for unrecognized country.
  # customization: required
  denied-sanctioned-countries: |
    - "XX"
  #
  # Allowed domain names for os updates
  # The list below is an example for Debian and Ubuntu, modify as per trusted images
  # customization: optional
  allowed-os-update-domains: |
    - "debian.map.fastlydns.net"
    - "debian.org"
    - "deb.debian.org"
    - "ubuntu.com"
    - "packages.cloud.google.com"
    - "security.ubuntu.com"
    - "northamerica-northeast1.gce.archive.ubuntu.com"
    - "northamerica-northeast2.gce.archive.ubuntu.com"
  #
  # the source IP ranges allowed to access the domains listed above
  # the ranges should match the values of the '*main-snet' setters configured earlier:
  #   - standard-nane1-nonp-main-snet
  #   - standard-nane2-nonp-main-snet
  #   - standard-nane1-pbmm-main-snet
  #   - standard-nane2-pbmm-main-snet
  # OR a list of more restrictive ranges within those subnets (for example, 10.1.1.5/32)
  allowed-os-update-source-ip-ranges: |
    - "10.1.0.0/21"
    - "10.1.8.0/21"
    - "10.1.128.0/21"
    - "10.1.136.0/21"
  #
  ##########################
  # DNS
  ##########################
  #
  # dns project id created during core-landing-zone package deployment
  # customization: required, obtain value from the core-landing-zone setters.yaml
  dns-project-id: dns-project-12345
  #
  # Clients Landing Zone fqdn. The "dns-name" must end with a "."
  # dns-name needs to receive delegation from the upper level of the domain example.com.
  # customization: required
  dns-name: "client-name.example.com."
  #
  # The nameservers below must be updated to match the same nameservers as the client DNS subzone
  # Cloud DNS creates NS and SOA records automatically when a zone is created and these cannot be changed
  # See https://cloud.google.com/dns/docs/zones#create-pub-zone
  dns-nameservers: |
    - "ns-cloud-a1.googledomains.com."
    - "ns-cloud-a2.googledomains.com."
    - "ns-cloud-a3.googledomains.com."
    - "ns-cloud-a4.googledomains.com."
  # CCCS Approved Services
  cccs-services: |
    - datastudio.googleapis.com
    - contentwarehouse.googleapis.com
    - automl.googleapis.com
    - language.googleapis.com
    - speech.googleapis.com
    - jobs.googleapis.com
    - translate.googleapis.com
    - videointelligence.googleapis.com
    - vision.googleapis.com
    - dialogflow.googleapis.com
    - aiplatform.googleapis.com
    - apigee.googleapis.com
    - apigeeconnect.googleapis.com
    - apigeeregistry.googleapis.com
    - endpoints.googleapis.com
    - appengine.googleapis.com
    - appengineflex.googleapis.com
    - appenginereporting.googleapis.com
    - compute.googleapis.com
    - cloudfunctions.googleapis.com
    - vpcaccess.googleapis.com
    - bigquery.googleapis.com
    - bigquerydatapolicy.googleapis.com
    - bigqueryconnection.googleapis.com
    - bigqueryreservation.googleapis.com
    - bigquerystorage.googleapis.com
    - bigquerymigration.googleapis.com
    - lifesciences.googleapis.com
    - dataflow.googleapis.com
    - dataproc.googleapis.com
    - pubsub.googleapis.com
    - pubsublite.googleapis.com
    - composer.googleapis.com
    - datafusion.googleapis.com
    - bigtabletableadmin.googleapis.com
    - spanner.googleapis.com
    - sql-component.googleapis.com
    - sqladmin.googleapis.com
    - firestore.googleapis.com
    - redis.googleapis.com
    - cloudbuild.googleapis.com
    - sourcerepo.googleapis.com
    - containerregistry.googleapis.com
    - containerscanning.googleapis.com
    - containersecurity.googleapis.com
    - containerthreatdetection.googleapis.com
    - containeranalysis.googleapis.com
    - container.googleapis.com
    - anthosconfigmanagement.googleapis.com
    - anthos.googleapis.com
    - anthospolicycontroller.googleapis.com
    - mesh.googleapis.com
    - gkehub.googleapis.com
    - krmapihosting.googleapis.com
    - cloudasset.googleapis.com
    - cloudbilling.googleapis.com
    - deploymentmanager.googleapis.com
    - datacatalog.googleapis.com
    - dns.googleapis.com
    - networkservices.googleapis.com
    - Network Intelligence Center
    - trafficdirector.googleapis.com
    - logging.googleapis.com
    - monitoring.googleapis.com
    - cloudprofiler.googleapis.com
    - cloudtrace.googleapis.com
    - accessapproval.googleapis.com
    - accesscontextmanager.googleapis.com
    - dlp.googleapis.com
    - cloudkms.googleapis.com
    - iap.googleapis.com
    - cloudidentity.googleapis.com
    - cloudresourcemanager.googleapis.com
    - servicecontrol.googleapis.com 
    - websecurityscanner.googleapis.com
    - binaryauthorization.googleapis.com
    - privateca.googleapis.com
    - recaptchaenterprise.googleapis.com
    - secretmanager.googleapis.com
    - securitycenter.googleapis.com
    - storage.googleapis.com
    - datastream.googleapis.com
    - eventarc.googleapis.com
  #
  ##########################
  # End of Configurations
  ##########################
