# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
# First, Grant GCP Role IAM service account admin on client management project to config-control SA a.k.a. yakima
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: projects/config-control-sa-iamserviceaccountadmin-client-management-project-id-permissions
  name: config-control-sa-iamserviceaccountadmin-client-management-project-id-permissions # kpt-set: ${management-namespace}-sa-iamserviceaccountadmin-${client-management-project-id}-permissions
  namespace: projects
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/client-management-project-id # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPolicyMember|projects|config-control-sa-iamserviceaccountadmin-client-management-project-id-permissions'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: client-management-project-id # kpt-set: ${client-management-project-id}
  role: roles/iam.serviceAccountAdmin
  member: "serviceAccount:service-management-project-number@gcp-sa-yakima.iam.gserviceaccount.com" # kpt-set: serviceAccount:service-${management-project-number}@gcp-sa-yakima.iam.gserviceaccount.com
---
# GCP SA
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata: # kpt-merge: config-control/client-name-config-control-sa
  name: client-name-config-control-sa # kpt-set: ${client-name}-${management-namespace}-sa
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: client-management-project-id # kpt-set: ${client-management-project-id}
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/client-management-project-id # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMServiceAccount|config-control|client-name-config-control-sa'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  # TODO: maybe remove client-name prefix to avoid exceeding the 30 chars limit for SA name
  displayName: client-name-config-control-sa # kpt-set: ${client-name}-${management-namespace}-sa
---
# Grant GCP Role Project IAM admin on client management project to GCP client-name-config-control-sa
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: projects/client-name-config-control-sa-projectiamadmin-client-management-project-id-permissions
  name: client-name-config-control-sa-projectiamadmin-client-management-project-id-permissions # kpt-set: ${client-name}-${management-namespace}-sa-projectiamadmin-${client-management-project-id}-permissions
  namespace: projects
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/client-management-project-id # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPolicyMember|projects|client-name-config-control-sa-projectiamadmin-client-management-project-id-permissions'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: client-management-project-id # kpt-set: ${client-management-project-id}
  role: roles/resourcemanager.projectIamAdmin
  member: "serviceAccount:client-name-config-control-sa@client-management-project-id.iam.gserviceaccount.com" # kpt-set: serviceAccount:${client-name}-${management-namespace}-sa@${client-management-project-id}.iam.gserviceaccount.com
---
# Grant GCP Role IAM service account admin on client management project to GCP client-name-config-control-sa
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: hierarchy/client-name-config-control-sa-iamserviceaccountadmin-client-folder-permissions
  name: client-name-config-control-sa-iamserviceaccountadmin-client-folder-permissions # kpt-set: ${client-name}-${management-namespace}-sa-iamserviceaccountadmin-client-folder-permissions
  namespace: hierarchy
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/client-management-project-id # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPolicyMember|hierarchy|client-name-config-control-sa-iamserviceaccountadmin-client-folder-permissions'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Folder
    name: clients.client-name # kpt-set: clients.${client-name}
  role: roles/iam.serviceAccountAdmin
  member: "serviceAccount:client-name-config-control-sa@client-management-project-id.iam.gserviceaccount.com" # kpt-set: serviceAccount:${client-name}-${management-namespace}-sa@${client-management-project-id}.iam.gserviceaccount.com
---
# K8S SA
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/client-name-config-control-sa-workload-identity-binding
  name: client-name-config-control-sa-workload-identity-binding # kpt-set: ${client-name}-${management-namespace}-sa-workload-identity-binding
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/client-management-project-id # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'iam.cnrm.cloud.google.com|IAMPartialPolicy|config-control|client-name-config-control-sa-workload-identity-binding'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  resourceRef:
    name: client-name-config-control-sa # kpt-set: ${client-name}-${management-namespace}-sa
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:management-project-id.svc.id.goog[cnrm-system/cnrm-controller-manager-client-name-config-control] # kpt-set: serviceAccount:${management-project-id}.svc.id.goog[cnrm-system/cnrm-controller-manager-${client-name}-${management-namespace}]
---
# K8S namespace
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /client-name-config-control
  name: client-name-config-control # kpt-set: ${client-name}-${management-namespace}
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/client-management-project-id # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: '|Namespace|default|client-name-config-control'
---
# Link GCP SA to K8S namespace
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata: # kpt-merge: client-name-config-control/configconnectorcontext.core.cnrm.cloud.google.com
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: client-name-config-control # kpt-set: ${client-name}-${management-namespace}
  annotations:
    cnrm.cloud.google.com/ignore-clusterless: "true"
    config.kubernetes.io/depends-on: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/client-management-project-id # kpt-set: resourcemanager.cnrm.cloud.google.com/namespaces/projects/Project/${client-management-project-id}
    internal.kpt.dev/upstream-identifier: 'core.cnrm.cloud.google.com|ConfigConnectorContext|client-name-config-control|configconnectorcontext.core.cnrm.cloud.google.com'
    cnrm.cloud.google.com/blueprint: 'kpt-pkg'
spec:
  googleServiceAccount: client-name-config-control-sa@client-management-project-id.iam.gserviceaccount.com # kpt-set: ${client-name}-${management-namespace}-sa@${client-management-project-id}.iam.gserviceaccount.com
