apiVersion: authorization.azure.upbound.io/v1beta1
kind: PolicyDefinition
metadata:
  labels:
    testing.upbound.io/example-name: example-auth
  name: pbmm-${managementgroupid}
spec:
  forProvider:
    displayName: "Deny Azure Bastion Hosts resource creation"
    policyDefinitionId: "4c4a5f27-de81-430b-b4e5-9cbd50595a87"
    mode: default
    parameters: | 
        {
            logAnalyticsWorkspaceIdforVMReporting: {
              value: logAnalyticsWorkspaceId
            }
            listOfMembersToExcludeFromWindowsVMAdministratorsGroup: {
              value: listOfMembersToExcludeFromWindowsVMAdministratorsGroup
            }
            listOfMembersToIncludeInWindowsVMAdministratorsGroup: {
              value: listOfMembersToIncludeInWindowsVMAdministratorsGroup
            }
            'logsEnabled-7f89b1eb-583c-429a-8828-af049802c1d9': {
              value: true
            }
            'metricsEnabled-7f89b1eb-583c-429a-8828-af049802c1d9': {
              value: false
            }
            listOfResourceTypesWithDiagnosticLogsEnabled: {
              value: [
                'Microsoft.AnalysisServices/servers'
                'Microsoft.ApiManagement/service'
                'Microsoft.Network/applicationGateways'
                'Microsoft.Automation/automationAccounts'
                // 'Microsoft.ContainerInstance/containerGroups'  # Removed since it doesn't have any logs
                'Microsoft.ContainerRegistry/registries'
                'Microsoft.ContainerService/managedClusters'
                'Microsoft.Batch/batchAccounts'
                'Microsoft.Cdn/profiles/endpoints'
                'Microsoft.CognitiveServices/accounts'
                'Microsoft.DocumentDB/databaseAccounts'
                'Microsoft.DataFactory/factories'
                'Microsoft.DataLakeAnalytics/accounts'
                'Microsoft.DataLakeStore/accounts'
                'Microsoft.EventGrid/eventSubscriptions'
                'Microsoft.EventGrid/topics'
                'Microsoft.EventHub/namespaces'
                'Microsoft.Network/expressRouteCircuits'
                'Microsoft.Network/azureFirewalls'
                'Microsoft.HDInsight/clusters'
                'Microsoft.Devices/IotHubs'
                'Microsoft.KeyVault/vaults'
                'Microsoft.Network/loadBalancers'
                'Microsoft.Logic/integrationAccounts'
                'Microsoft.Logic/workflows'
                'Microsoft.DBforMySQL/servers'
                //'Microsoft.Network/networkInterfaces' # Removed since it doesn't have any logs
                'Microsoft.Network/networkSecurityGroups'
                'Microsoft.DBforPostgreSQL/servers'
                'Microsoft.PowerBIDedicated/capacities'
                'Microsoft.Network/publicIPAddresses'
                'Microsoft.RecoveryServices/vaults'
                'Microsoft.Cache/redis'
                'Microsoft.Relay/namespaces'
                'Microsoft.Search/searchServices'
                'Microsoft.ServiceBus/namespaces'
                'Microsoft.SignalRService/SignalR'
                'Microsoft.Sql/servers/databases'
                //'Microsoft.Sql/servers/elasticPools' # Removed since it doesn't have any logs
                'Microsoft.StreamAnalytics/streamingjobs'
                'Microsoft.TimeSeriesInsights/environments'
                'Microsoft.Network/trafficManagerProfiles'
                //'Microsoft.Compute/virtualMachines' # Logs are collected through Microsoft Monitoring Agent
                //'Microsoft.Compute/virtualMachineScaleSets' Removed since it is not supported
                'Microsoft.Network/virtualNetworks'
                'Microsoft.Network/virtualNetworkGateways'
              ]
            }
          }
          enforcementMode: enforcementMode
        }
    policyType: Custom