#########
#
# Constraint: constraints/iam.allowedPolicyMemberDomains
#
# This list constraint defines one or more Cloud Identity or 
# Google Workspace customer IDs whose principals can be added to IAM policies.
# To get instructions workspace ID make sure you are logged in as the admin user for admin.google.com
# In your Google Admin console (at admin.google.com)...
# Go to Account settings > Profile.
# Next to Customer ID, find your organization's unique ID.
#
#########
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata: 
  name: allowed-policy-member-domain
  namespace: config-control # kpt-set: ${management-namespace}
  labels:
    guardrail: "true"
    guardrail-enforced: guardrail-06
spec:
  constraint: "constraints/iam.allowedPolicyMemberDomains"
  listPolicy:
    allow:
      all: true # set to false to disable
      values: # kpt-set: ${allowed-domain-members}
        - "asdasda"
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}