# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.     
#########
#
# Constraint: constraints/compute.disableGuestAttributesAccess
# 
# This boolean constraint disables Compute Engine API access 
# to the Guest Attributes of Compute Engine VMs belonging 
# to the organization, project, or folder where this constraint is set to True.
#
#########
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata: 
  name: disable-guest-attribute-access
  namespace: config-control # kpt-set: ${management-namespace}
  labels:
spec:
  constraint: "constraints/compute.disableGuestAttributesAccess"
  booleanPolicy:
    enforced: true
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}