#########
#
# Constraint: constraints/compute.restrictVpcPeering
# This list constraint defines the set of VPC networks 
# that are allowed to be peered with the VPC networks belonging to this project, folder, or organization.
# The allowed/denied list of networks must be identified in the form: 
# under:organizations/ORGANIZATION_ID, under:folders/FOLDER_ID, under:projects/PROJECT_ID, 
# or projects/PROJECT_ID/global/networks/NETWORK_NAME.
#
#########
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata: 
  name: restrict-vpc-peering
  namespace: config-control # kpt-set: ${management-namespace}
  labels:
    guardrail: "true"
    guardrail-enforced: guardrail-09
spec:
  constraint: "constraints/compute.restrictVpcPeering"
  listPolicy:
    allow:
      all: true # set to false to enable
      values:
      - under:folders/FOLDER_ID
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}  