name: solutions-validation
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    container: 
      image: gcr.io/config-management-release/nomos:stable
      options: --entrypoint ""
    steps:
      - name: nomos vet
        run: |
          nomos vet --no-api-server-check --source-format unstructured --path solutions/landing-zone/environments