name: solutions-validation
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    container: gcr.io/config-management-release/nomos:stable
    steps:
      - name: nomos vet
        options:
          entrypoint: ""
        run: |
          nomos vet --no-api-server-check --source-format unstructured --path solutions/landing-zone/environments