name: solutions-validation
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    # container: 
    #   image: gcr.io/config-management-release/nomos:stable
    #   options: --entrypoint ""
    steps:
      - name: checkout
        uses: actions/checkout@v1    
      - name: dir check
        run: ls
      - name: nomos vet
        run: |
          docker run gcr.io/config-management-release/nomos:stable --entrypoint "" vet --no-api-server-check --source-format unstructured --path solutions/landing-zone/environments