name: solutions-validation
on: [push]
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: check
        run: ls
  validate:
    runs-on: ubuntu-latest
    needs: workspace
    container: 
      image: gcr.io/config-management-release/nomos:stable
      options: --entrypoint ""
    steps:
      - name: dir check
        run: ls
      - name: nomos vet
        run: |
          nomos vet --no-api-server-check --source-format unstructured --path solutions/landing-zone/environments